services:
  clinica:
    build: .
    container_name: clinica
    ports:
      - "8080:8080"
    networks:
      - clinica-net
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
networks:
  clinica-net:
    driver: bridge